// Generated by tools/update_autodetect_corpus.py. Do not edit.
pub const shards = .{
    @import("detect_profiles_0.zig").profiles,
    @import("detect_profiles_1.zig").profiles,
    @import("detect_profiles_2.zig").profiles,
    @import("detect_profiles_3.zig").profiles,
    @import("detect_profiles_4.zig").profiles,
    @import("detect_profiles_5.zig").profiles,
    @import("detect_profiles_6.zig").profiles,
    @import("detect_profiles_7.zig").profiles,
    @import("detect_profiles_8.zig").profiles,
    @import("detect_profiles_9.zig").profiles,
};
